name: Test Tags Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout代码
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 确保拉取完整历史
          submodules: recursive  # 如果用到子模块

      # Step 5: 检测最近的标签
      - name: Detect Latest Git Tag
        shell: pwsh
        run: |
          $TAG = git describe --tags --abbrev=0 --always 2>$null
          if (-not $TAG) {
            $TAG = "no-tag"
          }
          echo "Detected Tag: $TAG"
          echo "tag=$TAG" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8
